require File.dirname(__FILE__) + '/acts_as_taggable_on_steroids/tag_list'
require File.dirname(__FILE__) + '/acts_as_taggable_on_steroids/tagging'
require File.dirname(__FILE__) + '/acts_as_taggable_on_steroids/tag'
require File.dirname(__FILE__) + '/acts_as_taggable_on_steroids/tags_helper'
require File.dirname(__FILE__) + '/acts_as_taggable_on_steroids/acts_as_taggable'
